#!/usr/bin/env python3
"""Give the MAIN world its own asset, avoiding cross-world script deduplication."""
from pathlib import Path

def build(root):
    source = "// Generated by scripts/build-web-extension.py; edit core.js or bridge.js.\n"
    source += (root / 'core.js').read_text() + "\n;\n" + (root / 'bridge.js').read_text()
    (root / 'bridge-main.js').write_text(source)

if __name__ == '__main__':
    build(Path(__file__).resolve().parent.parent)
